defaults:
  - _self_
  - override hydra/hydra_logging: disabled
  - override hydra/job_logging: disabled

env:
  id: "CartPole-v1"

algorithm:
  # General parameters
  name: "a3c"
  device: "cpu"
  seed: 42
  num_workers: 16
  gamma: 0.99
  max_rollout_length: 5
  total_timesteps: 500000

  # loss parameters
  value_loss_coef: 0.5
  entropy_coef: 0.0

  # Network architecture
  network:
    type: "mlp"  # Options: mlp, nature_cnn, recurrent
    hidden_sizes: [64, 64]

  # Optimizer configuration
  optimizer:
    learning_rate: 1e-3
    final_learning_rate: 1e-5
    adam_beta1: 0.9
    adam_beta2: 0.999
    adam_weight_decay: 0.0
    adam_amsgrad: false
    max_grad_norm: 0.5
    log_params_norm: false

wandb:
  track: true
  project: "a3c"
  run_name: "test_run"
